// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx4gOLvWoDEGpPO2Y7Jr-2PTXNs8y2TYs',
    appId: '1:251212949725:web:09af676b70db5fe6d99334',
    messagingSenderId: '251212949725',
    projectId: 'chat-app-714d7',
    authDomain: 'chat-app-714d7.firebaseapp.com',
    storageBucket: 'chat-app-714d7.appspot.com',
    measurementId: 'G-0WRNV1B901',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3DTFJ-4SCF5OracPuPCzSP700v55hNEc',
    appId: '1:251212949725:android:168b57f89c078ae2d99334',
    messagingSenderId: '251212949725',
    projectId: 'chat-app-714d7',
    storageBucket: 'chat-app-714d7.appspot.com',
  );
}
